# Generated by Django 5.2 on 2025-04-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecommande',
            name='commande',
        ),
        migrations.RemoveField(
            model_name='articlecommande',
            name='produit',
        ),
        migrations.AddField(
            model_name='panier',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='AdresseLivraison',
        ),
        migrations.DeleteModel(
            name='ArticleCommande',
        ),
    ]
